### ISSUE TITLE
Using my own models and animations instead of importing them from a ROM

### ISSUE THREAD

**Issue by ACIDULATED** [libsm64/libsm64#12]
I want to use my own models and animations instead of importing them from a ROM (I don't HAVE a ROM). Is that at all possible?

**Comment by jaburns** [comment]
It's not very straightforward, but with some hacking it's possible. You'd need to use Fast64 to create a model that would work as a patch in the original decompilation, and then bring the generated C files into this project, replacing the ones that are downloaded from the decomp by this script https://github.com/libsm64/libsm64/blob/master/import-mario-geo.py

I'd be happy accept PRs that make this process easier, but supporting custom models isn't a feature I'm personally interested in implementing.
