### ISSUE TITLE
addon will not work

### ISSUE THREAD

**Issue by blazebrown87221** [libsm64/libsm64#13]
I can't find it and I searched the name it still did not show
![image](https://user-images.githubusercontent.com/96564866/169098231-8abcfb48-fa00-4ade-a547-b50c9a949b97.png)

**Comment by Agent-11** [comment]
![skull-and-crossbones-emoji-by-twitter](https://user-images.githubusercontent.com/44549182/169160817-1ae74eec-d80c-4669-a397-2cd940a67d2f.png)

**Comment by jaburns** [comment]
Did you download the addon, and install it by clicking the "Install..." button in the preferences window there? If not, what exact steps did you follow to install it where you'd expect to see it in the list?

**Comment by walksanatora** [comment]
also this should be in the belender repo not the libsm64 repo
