### ISSUE TITLE
How to port this to other games

### ISSUE THREAD

**Issue by juanroman74454811** [libsm64/libsm64#16]
im trying to port this to like Roblox or something and i dont understand how to port this to Roblox

**Comment by Agent-11** [comment]
lol

**Comment by Zack-Green** [comment]
LOL,
Hey wait a second 
No it can't be

**Comment by juanroman74454811** [comment]
> LOL, Hey wait a second No it can't be

Roblox is coded on Lua. That means, if i do a BLJ, it will blast me away,

**Comment by jaburns** [comment]
You could do like the SM64 online JS port where they manually translated all the C code to JS, but do it to lua instead. You could maybe even write a C to Lua transpiler to automate that process. But it won't be an easy task!

**Comment by Zack-Green** [comment]
I was freaking out when I saw Agent 11 here

We're literally enemies
