### ISSUE TITLE
Export functions for setting Mario state

### ISSUE THREAD

**Issue by Brawmario** [libsm64/libsm64#30]
The library should export functions for directly setting a mario's state, like setting position, angle and forcefully dealing damage. These are essential for my  Godot Engine bindings of the lib: https://github.com/Brawmario/libsm64-godot

I've been using the following fork of this lib that implements this functionality: https://github.com/ckosmic/libsm64 . If wanted I could port these functions myself upstream.

**Comment by Brawmario** [comment]
Oh wow what timing, pull request #29 will already do that, hopefully it will get merged soon and I can go back to using this version of the lib.

To not make this go to waste, could I add my Godot addon the list of "Bindings and plugins" on the Readme?

**Comment by jaburns** [comment]
Absolutely, feel free to submit a PR with the godot link in the readme and I'll merge it!

**Comment by jaburns** [comment]
Added to README
