### ISSUE TITLE
Add license to project

### ISSUE THREAD

**Issue by Brawmario** [libsm64/libsm64#31]
There should definitely be a license to this project, providing it without one makes it very unclear what can be done with this library without potentially upsetting a contributor. This is especially important if this project is to continue to accept PRs from potential contributors, since it could very quickly become a legal nightmare even if we are all well meaning. The actual Super Mario 64 decompilation project finally settled with the CC0 1.0 license between its contributors last month in this commit: https://github.com/n64decomp/sm64/commit/66018e9f3caaa67399218971d61366cb3f7ba7d7 . I'd like to propose the same license for this project too.

**Comment by jaburns** [comment]
Sure, let's just do the same as the main decomp and make it CC0 1.0.
