### ISSUE TITLE
idk what this means help

### ISSUE THREAD

**Issue by SuperMarioYAHOOYAHOO** [libsm64/libsm64#39]
./import-mario-geo.py
Downloading https://raw.githubusercontent.com/n64decomp/sm64/06ec56df7f951f88da05f468cdcacecba496145a/actors/mario/geo.inc.c
Traceback (most recent call last):
  File "/c/users/coolm/documents/libsm64/./import-mario-geo.py", line 99, in <module>
    main()
  File "/c/users/coolm/documents/libsm64/./import-mario-geo.py", line 64, in main
    geo_inc_c = urllib.request.urlopen(GEO_URL).read().decode('utf8')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 541, in _open
    return self._call_chain(self.handle_open, 'unknown',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
make: *** [Makefile:45: src/decomp/mario/geo.inc.c] Error 1

help

**Comment by Brawmario** [comment]
That's very weird, what operating system are you on and what version of Python you have installed?

**Comment by SuperMarioYAHOOYAHOO** [comment]
> That's very weird, what operating system are you on and what version of Python you have installed?

i have python 3.11 and 3.10 and i am running windows 11.

**Comment by R3L14NT94** [comment]
I don't even know how to compile sm64 as a dll, since the instructions are too vague and isn't even clear on what it is I should do!?

**Comment by gdandsm64fan123** [comment]
bro described my exact problem

**Comment by jaburns** [comment]
Are you running this inside of mingw? You followed the steps on the decomp repo for setting up mingw, then inside of minglw ran the pacman command and then ran make?

**Comment by adiee5** [comment]
Please change it to "Python script doesnt work" so that it'd be obvous what is this about

**Comment by adiee5** [comment]
Hmm, the script in question wasn't updated in 3 years...

**Comment by jaburns** [comment]
@SuperMarioYAHOOYAHOO I'm gonna close this since I can't help without more context. Post in this issue thread again with more info if you have it.

**Comment by adiee5** [comment]
> @SuperMarioYAHOOYAHOO I'm gonna close this since I can't help without more context. Post in this issue thread again with more info if you have it.

Well this thing comes up, when one tries to compile libsm64

**Comment by jaburns** [comment]
> > @SuperMarioYAHOOYAHOO I'm gonna close this since I can't help without more context. Post in this issue thread again with more info if you have it.
> 
> Well this thing comes up, when one tries to compile libsm64

Are you running this inside of mingw? You followed the steps on the decomp repo for setting up mingw, then inside of minglw ran the pacman command and then ran make?

**Comment by adiee5** [comment]
> > > @SuperMarioYAHOOYAHOO I'm gonna close this since I can't help without more context. Post in this issue thread again with more info if you have it.
> > 
> > Well this thing comes up, when one tries to compile libsm64
> 
> Are you running this inside of mingw? You followed the steps on the decomp repo for setting up mingw, then inside of minglw ran the pacman command and then ran make?
> 

Yeah, I think that's what I did

**Comment by jaburns** [comment]
lol can you confirm with certainty? And maybe share the full log of what happens when you try to run that command? Is it identical to the OP?
