### ISSUE TITLE
Dynamic Surfaces?

### ISSUE THREAD

**Issue by Luminoso-256** [libsm64/libsm64#43]
Hello!

I've been trying to integrate libsm64 for a project, but I'm running into issues with the key requirement of being able to dynamically swap out the terrain surfaces. It seems that calling the surface init function again locks up Mario, but editing the array that surface init was given a pointer to after the fact similarly accomplishes nothing. 

Am I going about this wrong, or are the hacks going to have to be uglier for this to work?

**Comment by Brawmario** [comment]
I'm assuming you're talking about the static surfaces, right? Yeah, I don't think calling the static surfaces init function again after spawning in Mario is supported, if you want to have surfaces that you can change dynamicly you might have better luck with surface objects, you can then delete and recreate them if you want to change their properties. Maybe there could be a function to alter them after they are created with the ID, that would be interesting.

Also, about editing the array given as a pointer after the fact, libsm64 doesn't keep the pointer internally, it copies the data, so you can even delete it after calling the init function.

**Comment by Luminoso-256** [comment]
Alright, surface objects sound ideal. Are there any minimal(-ish) code samples for how working with those looks in the vein of the `Test` subdirectory in the repo?

**Comment by Brawmario** [comment]
I'm not home right now so I can't get examples, but using the surfaces objects functions is not too complicated, just that they also need the positioning along with the triangles, and can be updated through the ID.

One thing to note, you still need a "base" static surfaces world in order for the lib to work, you can't just use surfaces objects. The static surfaces can be just a flat plane but it needs to existm

**Comment by Luminoso-256** [comment]
Alright, thanks!

So would something along these lines
```cpp
SM64SurfaceObject so = {
            .transform = {
                    .position = {0,0,0},
                    .eulerRotation = {0,0,0},
            },  
            .surfaceCount = (uint32_t) surfaceCount,
            .surfaces = generatedSurfaces,
 };
 ```
  be more-or-less equivalent to a static surfaces call, minus the benefits?

**Comment by Brawmario** [comment]
Yes it would. Just remember to have a static surfaces world underneath your objects and have it extend to as far as your world needs to be horizontally, since sm64 creates invisible walls at the edges of the static surfaces.

**Comment by Luminoso-256** [comment]
Alright, thanks a ton!
One last semi-unrelated question, if you don't mind...
I've been trying to implement rendering Mario, and while it's mostly there, there's a couple vertices notably absent:
![image](https://user-images.githubusercontent.com/63971285/227790010-f8e5fe02-c743-4b65-935c-6d224d2d22a2.png)

The thing I'm integrating with has a batching system for rendering, so in my attempts to tie into that the code looks like this:
```cpp
for (int i = 0; i<3*(marioGeometry.numTrianglesUsed);i+=3){
        addColor4f(marioGeometry.color[i],marioGeometry.color[i+1],marioGeometry.color[i+2],1.0);
        addVertex(marioGeometry.position[i]/64,marioGeometry.position[i+1]/64,marioGeometry.position[i+2]/64);
}
```
(where 64 is a scale factor between SM64 coordinates and the host's that's consistent elsewhere.)
Any idea what I might be doing wrong? I suspect that I'm missing vertices somewhere but I'm not quite sure.

**Comment by Brawmario** [comment]
I see the problem, you're forgetting that for each triangle you have 9 numbers, not 3 (3 vertexes with each one being 3 numbers). This means that the position array buffer is actually 9 * triangles used. Maybe this section of my Godot add on makes this more apparent: https://github.com/Brawmario/libsm64-godot/blob/05f2230d0c9dd000904970ddf37fadcf9cc3ad09/extension/src/sm64_mario_internal.cpp#L167

**Comment by Luminoso-256** [comment]
Oh my, thank you so much! Gonna close this now since I think that's all the problems I've run into so far.
