### ISSUE TITLE
Texture memory mismatch

### ISSUE THREAD

**Issue by 2MuchTime247** [libsm64/libsm64#49]
In main.cpp, the amount of memory you allocate to "texture" is 0x3EE8 bytes (4 * SM64_TEXTURE_WIDTH * SM64_TEXTURE_HEIGHT) , but in load_tex_data.c, the function load_mario_textures_from_rom zeros out 0x2C000 bytes of texture (4 * ATLAS_WIDTH * ATLAS_HEIGHT).    That is more than is allocated.

If I'm misunderstanding let me know.   Thank you.

**Comment by Brawmario** [comment]
4 * SM64_TEXTURE_WIDTH * SM64_TEXTURE_HEIGHT is also 0x2C000, in fact SM64_TEXTURE_WIDTH  is equal to ATLAS_WIDTH  and SM64_TEXTURE_HEIGHT equal to ATLAS_HEIGHT, I'm not sure where the confusion stems from.

![image](https://github.com/libsm64/libsm64/assets/38757897/af32bb5b-3169-4747-be33-d7d83cc6a912)
![image](https://github.com/libsm64/libsm64/assets/38757897/bac23bf1-5ee3-417b-b0bf-7015635872e0)
![image](https://github.com/libsm64/libsm64/assets/38757897/e4c1b887-6b22-4e7d-b209-a8b49ea43057)

**Comment by 2MuchTime247** [comment]
Hmm I must have got mixed up somewhere, sorry.   Switching to the other variables in load_tex_data.c fixed a crash for me, but I also changed the way I'm zeroing out the memory so maybe that was part of it too.
