### ISSUE TITLE
Potential for mixing mechanics 

### ISSUE THREAD

**Issue by fhhcjfjug** [libsm64/libsm64#52]
Would it function if first person mechanics could be played in libsm64 putting first person mechanics in the library of assets; the mechanics coming from a free game like Freedoom? The potential start could be an inverse of that platforming in Doom with Mario. Bits of console commands and assets of FreeDoom could be setup, enemy and item spawning, like they load in FreeDoom but with 64's assets. Having a hotkey to change modes of play could be setup next so first person and platforming mechanics can switch on when selected.

**Comment by jaburns** [comment]
Yeah this sounds like the exact kind of thing libsm64 is for, putting Mario in other engines. Putting Mario in Freedoom would be a project on its own, of which libsm64 would be a dependency. Libsm64 itself isn't intended to integrate tightly with specific projects, or else it would become too complex.
