### ISSUE TITLE
Godot Reference Project

### ISSUE THREAD

**Issue by nightblade9** [libsm64/libsm64#53]
Hi! I see your `libsm64` org has Unity and Unreal starter projects.

FYI, there's a Godot project, c/o @Brawmario , over here: https://github.com/Brawmario/libsm64-godot

I haven't used it, but it looks functional. Would it be useful to keep a fork of it in your organization, so there's at least a reference project for Godot users?

Cheers,

**Comment by jaburns** [comment]
@Brawmario I could add you to the libsm64 organization and you could put the project here if you'd like. Also you could commit directly to the base libsm64 library if need be. In the mean time I'll add libsm64-godot to the README.

**Comment by nightblade9** [comment]
If you (both?) are okay with it, I have a "plug and play" working version of @Brawmario 's repository, here: https://github.com/nightblade9/libsm64-Godot-sample - I'd be happy to transfer that over to you.

It's just an unpacked sample with the files properly in place etc. You can hit "play" and run the game from source.

**Comment by Brawmario** [comment]
I think I'd rather keep my repo on my account for now, I don't see much reason to do otherwise. I still have interest in maintaining the addon myself and being linked on this project's README is good enough for me.

@nightblade9 I don't see much point in the repo you made, it looks like just what I make available in my Releases...

**Comment by nightblade9** [comment]
I'm planning to extend my version to include samples of things like an object that only responds to being stomped. Will come back once I figure it all out. (Please poke me if I forget.)

**Comment by nightblade9** [comment]
As of now, I have extended the sample somewhat. It includes:

- Click to play, no need to set up anything manually like the wiki instructions mention
- A sample block that interacts (dies) if you punch it
- A sample block that interacts (dies) if you stomp it
- Mario's victory dance if you stomp the block

I think these changes make it much easier to get started with the library. It took me a while to figure all this out.

I plan to update my sample project tomorrow with a cleaner version of these changes. Would you be interested in keeping a fork/copy or even ownership of it @jaburns ?

**Comment by Brawmario** [comment]
You can contribute these additions to my repo, I'd love to have these examples as separate demos in the project!

BTW, the "manual setup" is only necessary if you are directly cloning the project through Git, I make available a "Click to play" ready package of the project in the "Releases", as there's little point to keeping compiled binaries in version control.

**Comment by nightblade9** [comment]
Turns out you can just open it in Godot 4.2 and you get an option to automatically downgrade.

Done and pushed.
