### ISSUE TITLE
Other characters/enemies

### ISSUE THREAD

**Issue by vico93** [libsm64/libsm64#55]
Kinda a newbie question here, but can this library be used to add other characters (Yoshi, Luigi, and potentially others from DS version) and/or enemies instead of Mario?

**Comment by jaburns** [comment]
Mario's graphics are tied fairly tightly to his movement, so it wouldn't be a very easy project to reskin Mario. You'd have to just not render him and then manually re-implement all the animations, or use the data generated by an sm64 animation editor to patch the decompilation project used by the library. In short, it's not a goal of this library, no.
