### ISSUE TITLE
Vanish cap wall logic is missing

### ISSUE THREAD

**Issue by Naynuza** [libsm64/libsm64#56]
The collision handling for SURFACE_VANISH_CAP_WALLS seems to have been removed as part of camera code that was removed

https://github.com/n64decomp/sm64/blob/9921382a68bb0c865e5e45eb594d9c64db59b1af/src/engine/surface_collision.c#L112-L136
https://github.com/libsm64/libsm64/blob/0c73039d9770645ce4f0bc071f58e692038a7138/src/decomp/engine/surface_collision.c#L252

**Comment by jaburns** [comment]
Happy to merge a PR that fixes this
