### ISSUE TITLE
How Do I build this locally so I can change code and see what happens?

### ISSUE THREAD

**Issue by theonerm2** [libsm64/libsm64#9]

**Comment by theonerm2** [comment]
It's giving an error. make: cc: No such file or directory
make: *** [Makefile:39: build/src/debug_print.o] Error 127

**Comment by theonerm2** [comment]
Nevermind. I figured it out plus I made a version of this dll that can get the current mario action and set the mario action.

**Comment by Ndymario** [comment]
How did you fix this?
